### PR TITLE
Version bump libdigidocpp/qesteidutil/qdigidoc ebuilds

### PR DESCRIPTION
**Pull request by jaakristioja**
Added app-crypt/qesteidutil-3.13.10 and app-crypt/qdigidoc-3.13.5.

Notes:
- Changed `HOMEPAGE=` variables to point to https://github.com/open-eid/qdigidoc and https://github.com/open-eid/qesteidutil instead of the general project page https://github.com/open-eid/.
- Changed `mycmakeargs` to use `'-DBREAKPAD=FALSE'` instead of  `'-DBREAKPAD=""'` or it wouldn't build due to breakpad errors.
- I was unable to quickly verify whether the tarballs actually correspond to the signed git tag, because I did not figure out how these tarballs were created exactly. These seem to embed some submodule code and reorder stuff in .po files (when compared to the tagged commit), so it seems a bit strange. I also couldn't find any release scripts I could run to manually create the archives. I also haven't verified the signers GPG key.

### CODE REVIEW

**Comment by metsma** [comment]
Tar are create by travis https://github.com/open-eid/qdigidoc/blob/master/.travis.yml#L65

**Comment by metsma** [comment]
Breakpad has been removed from latest releases

https://github.com/open-eid/qdigidoc/releases/tag/v3.13.5

* Remove BreakPad

**Comment by jaakristioja** [comment]
Ah ok. Then it must have been the previous ebuilds currently in the overlay which needed breakpad-related change because they wouldn't build otherwise.

**Comment by jaakristioja** [comment]
Hmm... found some bugs. Please hold.

**Comment by jaakristioja** [comment]
Seems to work properly now.

**Comment by urmet** [comment]
Aha. Don't know why I didn't try `-DBREAKPAD=FALSE` myself. That fixes qesteidutil build errors I've been seeing.
qdigidoc does not need the breakpad define any more, so you can remove the whole `src_configure()` function from 3.14.5 version. qesteidutil still needs the define until the next release.

**Pull request merged**
