### PR TITLE
Update chrome-token-signing to 1.0.7

### PR DESCRIPTION
**Pull request by sainsaar**
This is needed to support the current
Estonian ID-cards with ECDSA.

### CODE REVIEW

**Comment by urmet** [comment]
I pushed some updates including chrome-token-signing-1.0.7 with some extra changes to install it for chrome/chromium too. Signing in chrome seems to work, authentication not. Might be something specific to my setup.

**Comment by metsma** [comment]
Maybe you can find hints here https://github.com/open-eid/linux-installer/blob/master/esteid-update-nssdb why auth does not work

**Comment by urmet** [comment]
Aha. I guess the `modutil -force -dbdir sql:$HOME/.pki/nssdb -add opensc-pkcs11 -libfile /usr/lib64/onepin-opensc-pkcs11.so -mechanisms FRIENDLY` command accomplishes roughly the same thing that firefox-pkcs11-loader extension does for firefox. Got auth working locally now :+1:

**Comment by urmet** [comment]
Did some more refinements. With aeac50bf1f284451e767b6174d4f75bbe6241190 Chrome auth works and gets configured automatically on next logon(probably should add a message about that). I guess this PR is no longer needed.

**Pull request closed without merging**
