### PR TITLE
Update qdigidoc3 to pass repoman QA check

### PR DESCRIPTION
**Pull request by monoidic**
Still needs a bunch of cherrypicked commits to actually compile on qt-5.11 though.

### CODE REVIEW

**Comment by metsma** [comment]
You cannot add digest these files. They are modified on time

**Comment by monoidic** [comment]
Those files are updated occasionally, invalidating the hashes, though a simple revision bump fixes that.

**Comment by urmet** [comment]
these hashes are already invalid :(

**Comment by monoidic** [comment]
Ah well. Maybe rapid -r bumps are a bit optimistic considering everything. Closing.

**Pull request closed without merging**
