### PR TITLE
Initial qdigidoc4 commit

### PR DESCRIPTION
**Pull request by monoidic**
This is based pretty heavily on the qdigidoc3 ebuild, it could probably be improved/may be missing bdeps/whatever, but at the moment, it seems to work.

### CODE REVIEW

**Comment by monoidic** [comment]
I moved the external files out of the overlay since repoman thinks files in the files directory should be <20k. Might be a bad idea to keep a bunch of large files in the git history?

**Comment by monoidic** [comment]
Reverted the changes mentioned above.

**Comment by lkraav** [comment]
I've noticed many times ebuilds written such larger sets of files are downloaded as a tarball from an externally hosted URL somewhere (sometimes ebuild author's own hosting account somewhere, github, or whatnot).

**Comment by monoidic** [comment]
I thought about that option, though I guess I don't consider myself very trustworthy.

**Comment by lkraav** [comment]
Maybe the tarball could be hosted at open-eid/gentoo repository somehow?

**Pull request merged**
